# networkCommon/semantic_codes.py
"""
semantic_codes.py

Defines shared numerical constants (IDs) for semantic types used by both
the interpreter and the compiler. This file should have no external dependencies
other than standard Python types.
"""

# --- Layer Types ---
LAYER_IDENTITY = 0
LAYER_LINEAR = 1
LAYER_CONV1D = 2
LAYER_CONV2D = 3
LAYER_CONV3D = 4
LAYER_CONVTRANSPOSE1D = 5
LAYER_CONVTRANSPOSE2D = 6
LAYER_CONVTRANSPOSE3D = 7
LAYER_LSTM = 8
LAYER_GRU = 9
LAYER_RNN = 10
LAYER_BATCHNORM1D = 11
LAYER_BATCHNORM2D = 12
LAYER_BATCHNORM3D = 13
LAYER_LAYERNORM = 14
LAYER_INSTANCENORM1D = 15
LAYER_INSTANCENORM2D = 16
LAYER_INSTANCENORM3D = 17
LAYER_GROUPNORM = 18
LAYER_MAXPOOL1D = 19
LAYER_MAXPOOL2D = 20
LAYER_MAXPOOL3D = 21
LAYER_AVGPOOL1D = 22
LAYER_AVGPOOL2D = 23
LAYER_AVGPOOL3D = 24
LAYER_ADAPTIVEMAXPOOL1D = 25
LAYER_ADAPTIVEMAXPOOL2D = 26
LAYER_ADAPTIVEMAXPOOL3D = 27
LAYER_ADAPTIVEAVGPOOL1D = 28
LAYER_ADAPTIVEAVGPOOL2D = 29
LAYER_ADAPTIVEAVGPOOL3D = 30
LAYER_DROPOUT = 31
LAYER_DROPOUT2D = 32
LAYER_DROPOUT3D = 33
LAYER_FLATTEN = 34
LAYER_UNFLATTEN = 35
LAYER_MULTIHEADATTENTION = 36
LAYER_TRANSFORMERENCODERLAYER = 37
LAYER_TRANSFORMERDECODERLAYER = 38
LAYER_EMBEDDING = 39
LAYER_UPSAMPLE = 40
LAYER_PIXELSHUFFLE = 41

# --- Activations ---
ACT_IDENTITY = 0
ACT_RELU = 1
ACT_SIGMOID = 2
ACT_TANH = 3
ACT_LEAKYRELU = 4
ACT_ELU = 5
ACT_GELU = 6
ACT_SILU = 7
ACT_SOFTMAX = 8
ACT_LOGSOFTMAX = 9
ACT_SELU = 10
ACT_MISH = 11
ACT_HARDSWISH = 12
ACT_HARDSIGMOID = 13
ACT_PRELU = 14
ACT_SOFTPLUS = 15

# --- Weight Initializers ---
W_INIT_DEFAULT = 0
W_INIT_NORMAL = 1
W_INIT_UNIFORM = 2
W_INIT_XAVIER_UNIFORM = 3
W_INIT_XAVIER_NORMAL = 4
W_INIT_KAIMING_UNIFORM = 5
W_INIT_KAIMING_NORMAL = 6
W_INIT_ORTHOGONAL = 7
W_INIT_SPARSE = 8
W_INIT_DIRAC = 9
W_INIT_CONSTANT = 10
W_INIT_EYE = 11
W_INIT_ZEROS = 12
W_INIT_ONES = 13

# --- Bias Initializers ---
B_INIT_DEFAULT = 0
B_INIT_ZEROS = 1
B_INIT_ONES = 2
B_INIT_CONSTANT = 3
B_INIT_NORMAL = 4
B_INIT_UNIFORM = 5

# --- Block Types ---
BLOCK_SEQUENTIAL = 0
BLOCK_RESIDUAL = 1
BLOCK_PARALLEL = 2
BLOCK_RECURRENT = 3
BLOCK_ATTENTION = 4
BLOCK_TRANSFORMER = 5

# --- Parameter Codes ---
PARAM_OUT_FEATURES = 0
PARAM_IN_FEATURES = 1
PARAM_OUT_CHANNELS = 2
PARAM_IN_CHANNELS = 3
PARAM_KERNEL_SIZE = 4
PARAM_STRIDE = 5
PARAM_PADDING = 6
PARAM_DILATION = 7
PARAM_GROUPS = 8
PARAM_HIDDEN_SIZE = 9
PARAM_INPUT_SIZE = 10
PARAM_NUM_LAYERS = 11
PARAM_DROPOUT = 12
PARAM_NUM_FEATURES = 13
PARAM_EPS = 14
PARAM_MOMENTUM = 15
PARAM_NUM_GROUPS = 16
PARAM_EMBEDDING_DIM = 17
PARAM_NUM_EMBEDDINGS = 18
PARAM_PADDING_IDX = 19
PARAM_NUM_HEADS = 20
PARAM_ATTN_DROPOUT = 21
PARAM_FF_DIM_MULTIPLIER = 22
PARAM_NORM_FIRST = 23
PARAM_NEGATIVE_SLOPE = 24
PARAM_OUTPUT_SIZE = 25
PARAM_DIM = 26

# --- Block Attribute Codes ---
BLOCK_ATTR_MERGE_INPUT_STRATEGY = 0
BLOCK_ATTR_SPLIT_OUTPUT_STRATEGY = 1
BLOCK_ATTR_PARALLEL_MERGE_OP = 2
BLOCK_ATTR_BLOCK_ACTIVATION = 3

# --- Flag Codes ---
FLAG_FREEZE = 0
FLAG_BATCH_FIRST = 1
FLAG_BIDIRECTIONAL = 2
FLAG_STATEFUL = 3
FLAG_TRACK_RUNNING_STATS = 4
FLAG_AFFINE = 5
FLAG_BIAS = 6 # Note: Opcode 27 was removed, LayerDefinition.bias is primary

# --- Conv Padding Types ---
CONV_PADDING_EXPLICIT = 0
CONV_PADDING_SAME = 1
CONV_PADDING_VALID = 2

# --- Shape Adapter Types ---
SHAPE_ADAPTER_NONE = 0
SHAPE_ADAPTER_FLATTEN = 1
SHAPE_ADAPTER_SQUEEZE = 2
SHAPE_ADAPTER_UNSQUEEZE = 3
SHAPE_ADAPTER_TRANSPOSE = 4

# --- Shape Compare Ops ---
SHAPE_OP_EQUAL = 0
SHAPE_OP_GREATER_THAN = 1
SHAPE_OP_LESS_THAN = 2
SHAPE_OP_NOT_EQUAL = 3
SHAPE_OP_GREATER_EQUAL = 4
SHAPE_OP_LESS_EQUAL = 5

# --- Weight Data Types ---
WEIGHT_DATA_WEIGHTS = 0
WEIGHT_DATA_BIASES = 1

# --- Attention Types ---
ATTN_MULTIHEAD_SELF = 0
ATTN_MULTIHEAD_CROSS = 1
ATTN_SCALED_DOT_PRODUCT = 2

# --- Aggregation Types ---
AGG_CONCATENATE = 0
AGG_ADD = 1
AGG_MULTIPLY = 2
AGG_GATED = 3
AGG_LAST = 4
AGG_MEAN = 5
AGG_SUM = 6
AGG_MAX = 7
AGG_ATTENTION = 8

# --- Stateful Persistence Types ---
STATEFUL_PERSIST_BATCH = 0
STATEFUL_PERSIST_EPOCH = 1
STATEFUL_PERSIST_AGENT = 2

# --- RNN Cell Types ---
RNN_CELL_SIMPLE = 0
RNN_CELL_LSTM = 1
RNN_CELL_GRU = 2
RNN_CELL_CUSTOM = 3

# --- RNN State Types ---
RNN_STATE_HIDDEN = 0
RNN_STATE_CELL = 1
RNN_STATE_BOTH = 2

# --- RNN State Init Types ---
RNN_INIT_ZEROS = 0
RNN_INIT_ONES = 1
RNN_INIT_NORMAL = 2
RNN_INIT_UNIFORM = 3
RNN_INIT_FROM_INPUT = 4
RNN_INIT_LEARNED = 5

# --- Plasticity Rules ---
PLASTICITY_HEBBIAN = 0
PLASTICITY_OJA = 1
PLASTICITY_BCM = 2
PLASTICITY_STDP = 3

# --- Plasticity Targets ---
PLASTICITY_TARGET_WEIGHTS = 0
PLASTICITY_TARGET_BIASES = 1
PLASTICITY_TARGET_BOTH = 2

# --- Entity Types ---
ENTITY_BLOCK = 0
ENTITY_LAYER = 1
ENTITY_PLASTICITY_RULE = 2
ENTITY_INTRINSIC_REWARD = 3
ENTITY_POLICY_HEAD = 4
ENTITY_COMPARATOR = 5
ENTITY_PREDICTOR = 6
ENTITY_MEMORY_BUFFER = 7
ENTITY_NOVELTY_MODULE = 8
ENTITY_AGENT_OUTPUT = 9 # Added for resolving final agent outputs

# --- Plasticity Modulation Effects ---
PLASTICITY_MOD_MULTIPLICATIVE = 0
PLASTICITY_MOD_ADDITIVE = 1
PLASTICITY_MOD_GATING = 2
PLASTICITY_MOD_METAPLASTICITY = 3

# --- Memory Buffer Types ---
MEM_FIFO = 0
MEM_RESERVOIR = 1
MEM_PRIORITY = 2
MEM_EPISODIC = 3

# --- Memory Operations ---
MEM_OP_WRITE = 0
MEM_OP_READ_RECENT = 1
MEM_OP_READ_SAMPLE = 2
MEM_OP_READ_SIMILARITY = 3
MEM_OP_CLEAR = 4
MEM_OP_GET_STATE = 5

# --- Predictor Model Types ---
PRED_MODEL_LINEAR = 0
PRED_MODEL_MLP = 1
PRED_MODEL_RNN = 2
PRED_MODEL_ENSEMBLE = 3
PRED_MODEL_BAYESIAN = 4
PRED_MODEL_COPY_INPUT = 5
PRED_MODEL_ZERO = 6

# --- Comparison Metrics ---
METRIC_MSE = 0
METRIC_MAE = 1
METRIC_KL_DIVERGENCE = 2
METRIC_COSINE_DISTANCE = 3
METRIC_L1_NORM = 4
METRIC_L2_NORM = 5
METRIC_BCE = 6

# --- Novelty Methods ---
NOVELTY_COUNT_BASED = 0
NOVELTY_RND = 1
NOVELTY_KNN = 2
NOVELTY_DENSITY_BASED = 3
NOVELTY_PRED_ERROR_BASED = 4

# --- Signal Purposes ---
SIGNAL_PURPOSE_MODULATE_PLASTICITY = 0
SIGNAL_PURPOSE_INFLUENCE_POLICY = 1
SIGNAL_PURPOSE_GATE_ACTIVITY = 2
SIGNAL_PURPOSE_UPDATE_TARGET = 3
SIGNAL_PURPOSE_ATTENTION_WEIGHT = 4
SIGNAL_PURPOSE_SET_PARAMETER = 5
SIGNAL_PURPOSE_PROVIDE_REWARD = 6

# --- Action Space Types ---
ACTION_SPACE_DISCRETE = 0
ACTION_SPACE_CONTINUOUS = 1
ACTION_SPACE_MIXED = 2
ACTION_SPACE_BINARY = 3

# --- Policy Connection Types ---
POLICY_CONN_DIRECT_LOGITS = 0
POLICY_CONN_VALUE_ESTIMATE = 1
POLICY_CONN_ADVANTAGE_ESTIMATE = 2
POLICY_CONN_BIAS = 3
POLICY_CONN_MODULATOR = 4